"""empty message

Revision ID: 3195e62146f5
Revises: 
Create Date: 2020-11-23 10:01:43.273377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3195e62146f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oscars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oscars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oscar', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='oscars_pkey'),
    sa.UniqueConstraint('oscar', name='oscars_oscar_key')
    )
    # ### end Alembic commands ###
